server:
  port: 88
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: admin_route
          uri: lb://mall-admin
          order: 2
          predicates:
            - Path=/admin/**
        - id: product_route
          uri: lb://mall-product
          order: 1
          predicates:
            - Path=/*/product/**
        - id: member_route
          uri: lb://mall-member
          order: 1
          predicates:
            - Path=/*/member/**
        - id: coupon_route
          uri: lb://mall-coupon
          order: 1
          predicates:
            - Path=/*/coupon/**
        - id: thirdparty_route
          uri: lb://mall-thirdparty
          order: 1
          predicates:
            - Path=/*/thirdparty/**
