server:
  port: 88
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: admin_route
          uri: lb://mall-admin
          order: 2
          predicates:
            - Path=/admin/**

        - id: product_route
          uri: lb://mall-product
          order: 1
          predicates:
            - Path=/*/product/**
        - id: product_prod_route
          uri: lb://mall-product
          order: 1
          predicates:
            - Host=mall.com

        - id: member_route
          uri: lb://mall-member
          order: 1
          predicates:
            - Path=/*/member/**

        - id: coupon_route
          uri: lb://mall-coupon
          order: 1
          predicates:
            - Path=/*/coupon/**

        - id: ware_route
          uri: lb://mall-ware
          order: 1
          predicates:
            - Path=/*/ware/**

        - id: search_route
          uri: lb://mall-search
          order: 1
          predicates:
            - Path=/*/search/**

        - id: thirdparty_route
          uri: lb://mall-thirdparty
          order: 1
          predicates:
            - Path=/*/thirdparty/**
        - id: product_prod_route
          uri: lb://mall-product
          order: 1
          predicates:
            - Host=thirdparty.mall.com

        - id: product_auth_route
          uri: lb://mall-auth
          order: 1
          predicates:
            - Host=auth.mall.com

        - id: product_cart_route
          uri: lb://mall-cart
          order: 1
          predicates:
            - Host=cart.mall.com
